apiVersion: apps/v1
kind: Deployment
metadata:
  name: openspeedtest
  labels:
    app: openspeedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openspeedtest
  template:
    metadata:
      labels:
        app: openspeedtest
    spec:
      containers:
      - name: openspeedtest
        image: openspeedtest/latest
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: openspeedtest
spec:
  selector:
    app: openspeedtest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openspeedtest-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: speed.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openspeedtest
            port:
              number: 80
